config/routes.rb
Rails.application.routes.draw do

  resources :companies, only: [:index]
  resources :jobs, only: [:index]
  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :jobs, dependent: :destroy

  def index
    @companies = Company.includes(:jobs)
  end

  def market_names
    markets.map { |market| market['name'] }
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company
  validates_presence_of :company_id

  def company_name
    return unless company_id
    company.name
  end

  def company_logo
    return unless company_id
    company.logo
  end

  def company_website
    return unless company_id
    company.website
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <%= render 'layouts/quote' %>
    <table id='companiesTable' class='table' cellspacing='0' width='100%'%>
      <thead>
      <th class='col-md-2'>Name</th>
      <th class='col-md-2'>Product</th>
      <th class='col-md-4'>Markets</th>
      <th class='col-md-1'>Size</th>
      <th class='col-md-3'>Hiring</th>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
        <tr>
          <td>
            <span class='hidden'>
              <%= company.name %>
            </span>
            <span>
              <%= link_to image_tag(company.thumbnail, class: 'company_logo', alt: company.name), company.website, :target=>'_blank' %>
            </span>
            <div class="company_name"><%= company.name %></div>
          </td>
          <td><%= company.concept %></td>
          <td>
            <% company.market_names.each do |market| %>
              <div class='company market'>
                <%= market.split.map(&:capitalize).join(' ') %>
              </div>
            <% end %>
          </td>
          <td>
            <div class='company size'>
              <%= company.size %>
            </div>
          </td>
          <td>
            <span class='hidden'>
              <%= company.jobs.count %>
            </span>
            <!-- TODO: link to actual postings on company websites instead of angellist urls -->
            <% company.jobs.each do |job| %>
              <div class='company jobs'>
                <%= link_to job.title.split.map(&:capitalize).join(' '), job.angellist_url, :target => "_blank" %>
              </div>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/jobs/index.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <%= render 'layouts/quote' %>
    <table id='companiesTable' class='table' cellspacing='0' width='100%'%>
      <thead>
      <th class='col-md-3'>Title</th>
      <th class='col-md-2'>Role Type</th>
      <th class='col-md-2'>Skill Type</th>
      <th class='col-md-2'>Salary</th>
      <th class='col-md-2'>Equity</th>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td>
              <span class='hidden'>
                <%= job.title %>
              </span>
              <div class='job_display_title'>
                <%= job.decorate.job_title %>
              </div>
            </td>
            <td>
              <% if job.role_type %>
                <div class='job role_type'>
                  <%= job.decorate.job_role_type %>
                </div>
              <% end %>
            </td>
            <td>
              <% if job.skill_type %>
                <div class='job skill_type'>
                  <%= job.decorate.job_skill_type %>
                </div>
              <% end %>
            </td>
            <td>
              <div class='job salary'>
                <%= job.decorate.job_salary %>
              </div>
            </td>
            <td>
              <% if job.equity[0] != nil %>
                <div class='job equity'>
                  <%= job.decorate.job_equity %>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container-fluid footer">
<div class='row' id="footer">
  <div class="col-xs-0 col-md-3">
  </div>
  <div class="col-xs-12 col-md-6">
    <div class="row">
      <div class="col-xs-6 col-md-6" id="footer-left">
        <ul class="nav navbar-nav bottom">
          <li><%= facebook_button %></li>
          <li><%= twitter_button %></li>
        </ul>
      </div>
      <div class="col-xs-6 col-md-6" id="footer-right">
        <ul class="nav contact">
          <li><h2 id="page_name_footer">VANCOUVER STARTUP JOBS</h2></li>
          <li><p>Made in Vancouver, BC</p></li>
          <li><a type="button" href='https://twitter.com/Danny_MacD' class="btn btn-primary contact-btn" target="_blank">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-xs-0 col-md-3">
  </div>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div class='navbar navbar-default row'>
    <div class="col-xs-0 col-md-3">
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-7">
<!--         TODO: Refactor so that logo and wordmark are contained in same link_to helper -->
          <%= link_to "V", root_path, class: "circle" %>
          <%= link_to "VANCOUVER STARTUP JOBS", root_path, id: "page_name_header" %>
        </div>
        <div class="col-md-5">
          <ul class="nav navbar-nav top">
            <li><%= link_to "Startups", companies_path %></li>
            <li><%= link_to "Jobs", jobs_path %></li>
<!--             <li><%= link_to "Resources", '#' %></li> -->
          </ul>
        </div>
      </div>
    </div>
    <div class="col-xs-0 col-md-3">
    </div>
  </div>
</div>

app/views/layouts/_quote.html.erb
<div class='quote'>
  <h3 id='front_quote'>
    "With all respect to Palo Alto, life in a semi-arid industrial park</br>
    isn’t for everyone (even if you can get some really good tacos)."
  </h3>
  <p id='quote_source'>—Ryan Holmes, CEO at Hootsuite</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VanStartups</title>
  <link href='http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' rel='stylesheet'>
<!--   <link href='http://maxcdn.bootstrapcdn.com/bootswatch/3.3.0/flatly/bootstrap.min.css' rel='stylesheet'> -->
  <link rel='stylesheet' 
  href='http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css'>
  <link href='http://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.js' rel='stylesheet'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Vollkorn:400italic,400' rel='stylesheet' type='text/css'>
  <link href='http://cdn.datatables.net/responsive/1.0.3/css/dataTables.responsive.css' rel='stylesheet'>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
  <script type='text/javascript' 
  src='http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js'></script>
  <script type='text/javascript' 
  src='http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'></script>
  <script type="text/javascript" src='http://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.js'></script>
  </head>
  <script type="text/javascript" src="http://cdn.datatables.net/responsive/1.0.3/js/dataTables.responsive.js"></script>
<body>
  <%= render 'layouts/header' %>
  <div class='container-fluid'>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>